spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oradb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: password

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update

